name: Waka Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 */1 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: true
          SHOW_PROJECTS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_OS: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE: true
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SYMBOL_VERSION: true

          
